default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: wiki_development

test:
  <<: *default
  database: wiki_test

production:
  <<: *default
  database: wiki_production
  username: wiki
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
